### ISSUE TITLE
calling the example code fails.

### ISSUE THREAD

**Issue by jhoughjr** [nebrius/raspi-onewire#1]
/home/pi/sensor-server/node_modules/raspi-onewire/dist/index.js:52
        return deviceID.join('-');
                        ^

TypeError: Cannot read property 'join' of undefined
    at OneWire._convertIDToMappingKey (/home/pi/sensor-server/node_modules/raspi-onewire/dist/index.js:52:25)
    at OneWire._getNameFromID (/home/pi/sensor-server/node_modules/raspi-onewire/dist/index.js:55:43)
    at OneWire.readAllAvailable (/home/pi/sensor-server/node_modules/raspi-onewire/dist/index.js:123:56)

**Comment by jhoughjr** [comment]
My bad, Wasn't paying attention to the sample code.
